name: GitHub Pages

on:
  push:
    branches:
      - main
env:
  CI: true

jobs:
  check:
    name: Checklist
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Install Dependencies
        run: npm ci

      - uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/apps/getlab
